### ISSUE TITLE
Header NavBar Bug

### ISSUE THREAD

**Issue by NoMoneyDev** [PanidaRumriankit/SOS13#1]
NavBars works fine until you click on logo and come back to different page.
<img width="478" alt="Screenshot 2567-06-18 at 11 51 11 PM" src="https://github.com/PanidaRumriankit/SOS13/assets/89171527/b899bda2-49c0-4018-a2e8-5891d5145efb">
Image shows that there are 2 page selected at the same time.

**Comment by PanidaRumriankit** [comment]
fixed
